# config/config.py
import os

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

MIN_TRAIN_DATA = 1000
MIN_SIMILARITY_DATA = 100

SIMILARITY_THRESHOLD = 0.90
MAX_RESPONSE_LENGTH = 200
MAX_DECOMPOSE_DEPTH = 10
MAX_DB_RECORDS = 5000